version: "3.8"

services:
  cas_db:
    container_name: "cas_db"
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - ./cas_db_data:/var/lib/postgresql/data
      - ./cas_db_log:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - cas

  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 2s
      timeout: 2s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis_cache.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - cas

  flower_dashboard:
    container_name: "flower_dashboard"
    image: mher/flower
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    networks:
      - cas

networks:
  cas:
    driver: bridge
