"""migration

Revision ID: 060a12d8ab1d
Revises: d2077004757d
Create Date: 2023-07-10 03:10:45.809357

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '060a12d8ab1d'
down_revision = 'd2077004757d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'is_all_comments_available')
    op.drop_column('customer', 'is_all_reviews_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('is_all_reviews_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('is_all_comments_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
