"""similarity_analysis_tables migration

Revision ID: 12cde90b8230
Revises: 14c04dd9deaa
Create Date: 2023-07-09 08:55:28.860494

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12cde90b8230'
down_revision = '14c04dd9deaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_similarity_analysis',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('similarity_reviews_value', sa.Float(), nullable=False),
    sa.Column('similarity_comments_value', sa.Float(), nullable=False),
    sa.Column('datetime_formation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('customer_name_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version_mark', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.ForeignKeyConstraint(['customer_name_id'], ['customer.name_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_similarity_analysis',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('similarity_reviews_value', sa.Float(), nullable=False),
    sa.Column('similarity_comments_value', sa.Float(), nullable=False),
    sa.Column('datetime_formation', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('customer_name_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version_mark', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.ForeignKeyConstraint(['customer_name_id'], ['customer.name_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customer_general_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_general_analysis',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('datetime_formation', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('count_all_comments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count_all_reviews', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sentiment_all_comments_analysis_positive', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_comments_analysis_negative', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_comments_analysis_neutral', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_comments_analysis_skip', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_comments_analysis_speech', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_reviews_analysis_positive', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_reviews_analysis_negative', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_reviews_analysis_neutral', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_reviews_analysis_skip', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_all_reviews_analysis_speech', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('similarity_analysis_all_comments', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('similarity_analysis_all_reviews', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('customer_name_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version_mark', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_name_id'], ['customer.name_id'], name='customer_general_analysis_customer_name_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer_general_analysis_pkey')
    )
    op.drop_table('product_similarity_analysis')
    op.drop_table('customer_similarity_analysis')
    # ### end Alembic commands ###
