"""regional_location migration

Revision ID: 14c04dd9deaa
Revises: 3b598d3ee4cb
Create Date: 2023-07-08 17:15:04.789698

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '14c04dd9deaa'
down_revision = '3b598d3ee4cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regional_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('country_ru', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('country_en', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city_ru', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city_en', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regional_location')
    # ### end Alembic commands ###
