"""Migration

Revision ID: a489869a14f6
Revises: a85e96e9ef86
Create Date: 2023-07-03 20:55:02.732501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a489869a14f6'
down_revision = 'a85e96e9ef86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
