"""migration

Revision ID: 0b652122f657
Revises: 12cde90b8230
Create Date: 2023-07-09 09:05:05.772745

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0b652122f657'
down_revision = '12cde90b8230'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_similarity_analysis', sa.Column('product_name_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.drop_constraint('product_similarity_analysis_customer_name_id_fkey', 'product_similarity_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'product_similarity_analysis', 'product', ['product_name_id'], ['name_id'])
    op.drop_column('product_similarity_analysis', 'customer_name_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_similarity_analysis', sa.Column('customer_name_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_similarity_analysis', type_='foreignkey')
    op.create_foreign_key('product_similarity_analysis_customer_name_id_fkey', 'product_similarity_analysis', 'customer', ['customer_name_id'], ['name_id'])
    op.drop_column('product_similarity_analysis', 'product_name_id')
    # ### end Alembic commands ###
