"""migration

Revision ID: 0d1004d74de5
Revises: f512b5e8c07b
Create Date: 2023-07-09 11:25:23.557259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0d1004d74de5'
down_revision = 'f512b5e8c07b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
