"""Migration

Revision ID: a85e96e9ef86
Revises: f512c266f41f
Create Date: 2023-07-03 18:45:19.570283

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a85e96e9ef86'
down_revision = 'f512c266f41f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_customer_name_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('review_customer_name_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_evaluated_product_name_id_fkey', 'review', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('review_evaluated_product_name_id_fkey', 'review', 'product', ['evaluated_product_name_id'], ['name_id'])
    op.create_foreign_key('review_customer_name_id_fkey', 'review', 'customer', ['customer_name_id'], ['name_id'])
    op.create_foreign_key('comment_customer_name_id_fkey', 'comment', 'customer', ['customer_name_id'], ['name_id'])
    # ### end Alembic commands ###
