"""migration

Revision ID: d2077004757d
Revises: 0d1004d74de5
Create Date: 2023-07-10 03:02:28.557163

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd2077004757d'
down_revision = '0d1004d74de5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_all_customers_information_available_for_product')
    op.drop_column('review', 'is_all_commenting_customers_available')
    op.drop_column('review', 'count_user_recommend_review')
    op.drop_column('review', 'count_comments_review')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('count_comments_review', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('count_user_recommend_review', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('is_all_commenting_customers_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('is_all_customers_information_available_for_product', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
