components:
  schemas:
    CustomerReputationAnalysisValue:
      properties:
        analysis_value:
          description: Customer analysis value
          title: Analysis Value
          type: number
        reputation:
          description: Customer reputation value
          title: Reputation
          type: integer
      required:
      - reputation
      - analysis_value
      title: Value of customer analysis mapped to customer reputation
      type: object
    CustomersForAllCategoriesAnalysis:
      properties:
        analysis_value_avg:
          description: Average value of the analysis for the customer across all reviews
            / comments
          title: Analysis Value Avg
          type: number
        customers_count:
          description: Count of customers of the product
          minimum: 0.0
          title: Customers Count
          type: integer
        href_category_1:
          description: Href to the first level category
          title: Href Category 1
          type: string
        href_category_2:
          description: Href to the second level category
          title: Href Category 2
          type: string
        href_category_3:
          description: Href to the third level category
          title: Href Category 3
          type: string
        href_category_4:
          description: Href to the fourth level category
          title: Href Category 4
          type: string
        product_fullname:
          description: The full name of the analysis product
          title: Product Fullname
          type: string
        ru_category_1:
          description: Title of the first level category in russian
          title: Ru Category 1
          type: string
        ru_category_2:
          description: Title of the second level category in russian
          title: Ru Category 2
          type: string
        ru_category_3:
          description: Title of the third level category in russian
          title: Ru Category 3
          type: string
        ru_category_4:
          description: Title of the fourth level category in russian
          title: Ru Category 4
          type: string
      required:
      - ru_category_1
      - href_category_1
      - ru_category_2
      - href_category_2
      - ru_category_3
      - href_category_3
      - ru_category_4
      - href_category_4
      - product_fullname
      - customers_count
      - analysis_value_avg
      title: Analysis value customers across all categories
      type: object
    CustomersForAllCategoriesBaseAnalysis:
      properties:
        customers_count:
          description: Count of customers of the product
          minimum: 0.0
          title: Customers Count
          type: integer
        href_category_1:
          description: Href to the first level category
          title: Href Category 1
          type: string
        href_category_2:
          description: Href to the second level category
          title: Href Category 2
          type: string
        href_category_3:
          description: Href to the third level category
          title: Href Category 3
          type: string
        href_category_4:
          description: Href to the fourth level category
          title: Href Category 4
          type: string
        product_fullname:
          description: The full name of the analysis product
          title: Product Fullname
          type: string
        ru_category_1:
          description: Title of the first level category in russian
          title: Ru Category 1
          type: string
        ru_category_2:
          description: Title of the second level category in russian
          title: Ru Category 2
          type: string
        ru_category_3:
          description: Title of the third level category in russian
          title: Ru Category 3
          type: string
        ru_category_4:
          description: Title of the fourth level category in russian
          title: Ru Category 4
          type: string
      required:
      - ru_category_1
      - href_category_1
      - ru_category_2
      - href_category_2
      - ru_category_3
      - href_category_3
      - ru_category_4
      - href_category_4
      - product_fullname
      - customers_count
      title: Analysis customers across all categories
      type: object
    GroupRegionallyAllCustomerAnalysis:
      properties:
        analysis_value_avg:
          description: Average value of the analysis for the customer across all reviews
            / comments
          title: Analysis Value Avg
          type: number
        city_en:
          description: Customer city in english
          title: City En
          type: string
        city_ru:
          description: Customer city in russian
          title: City Ru
          type: string
        country_en:
          description: Customer country in english
          title: Country En
          type: string
        country_ru:
          description: Customer country in russian
          title: Country Ru
          type: string
        latitude:
          description: Latitude of the customer region
          title: Latitude
          type: number
        longitude:
          description: Longitude of the customer region
          title: Longitude
          type: number
        object_count:
          description: Count of reviews / comments on the analysis by region
          minimum: 0.0
          title: Object Count
          type: integer
      required:
      - country_ru
      - country_en
      - city_ru
      - city_en
      - latitude
      - longitude
      - object_count
      - analysis_value_avg
      title: Customer analysis values by region
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: Customer Analysis Service API
  version: 1.0.0
openapi: 3.0.2
paths:
  /api/v1/analysis_interests/comments:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0433\u0440\u0443\
        \u043F\u043F\u0438\u0440\u043E\u0432\u043A\u0443 \u043F\u043E \u0432\u0441\
        \u0435\u043C \u0438\u043D\u0442\u0435\u0440\u0435\u0441\u0430\u043C \u043A\
        \u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0442\u043E\u0440\u043E\u0432 \u043F\
        \u0440\u043E\u0434\u0443\u043A\u0442\u0430."
      operationId: customer_interest_comments_api_v1_analysis_interests_comments_get
      parameters:
      - in: query
        name: product_name_id
        required: true
        schema:
          title: Product Name Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CustomersForAllCategoriesBaseAnalysis'
                title: Response Customer Interest Comments Api V1 Analysis Interests
                  Comments Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Commentators interests
      tags:
      - analysis_interests
  /api/v1/analysis_interests/reviews:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0433\u0440\u0443\
        \u043F\u043F\u0438\u0440\u043E\u0432\u043A\u0443 \u043F\u043E \u0432\u0441\
        \u0435\u043C \u0438\u043D\u0442\u0435\u0440\u0435\u0441\u0430\u043C \u0440\
        \u0435\u0432\u044C\u044E\u0435\u0440\u043E\u0432 \u043F\u0440\u043E\u0434\u0443\
        \u043A\u0442\u0430."
      operationId: customer_interests_reviews_api_v1_analysis_interests_reviews_get
      parameters:
      - in: query
        name: product_name_id
        required: true
        schema:
          title: Product Name Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CustomersForAllCategoriesBaseAnalysis'
                title: Response Customer Interests Reviews Api V1 Analysis Interests
                  Reviews Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Reviewers interests
      tags:
      - analysis_interests
  /api/v1/analysis_sentiments/comments/category:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0441\u0435\u043D\
        \u0442\u0438\u043C\u0435\u043D\u0442 \u0430\u043D\u0430\u043B\u0438\u0437\
        \ \u043A\u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0442\u043E\u0440\u043E\
        \u0432 \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0430 \u0441\u0433\u0440\
        \u0443\u043F\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0439 \u043F\
        \u043E \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u044F\u043C"
      operationId: customer_sentiment_comments_category_api_v1_analysis_sentiments_comments_category_get
      parameters:
      - in: query
        name: product_name_id
        required: true
        schema:
          title: Product Name Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CustomersForAllCategoriesAnalysis'
                title: Response Customer Sentiment Comments Category Api V1 Analysis
                  Sentiments Comments Category Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Commentators sentiments by category
      tags:
      - analysis_sentiments
  /api/v1/analysis_sentiments/comments/region:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0441\u0435\u043D\
        \u0442\u0438\u043C\u0435\u043D\u0442 \u0430\u043D\u0430\u043B\u0438\u0437\
        \ \u043A\u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0442\u043E\u0440\u043E\
        \u0432 \u043F\u0440\u043E\u0434\u0443\u043A\u0442\u0430 \u0441\u0433\u0440\
        \u0443\u043F\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0439 \u043F\
        \u043E \u0440\u0435\u0433\u0438\u043E\u043D\u0430\u043C"
      operationId: customer_sentiment_comments_region_api_v1_analysis_sentiments_comments_region_get
      parameters:
      - in: query
        name: product_name_id
        required: true
        schema:
          title: Product Name Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GroupRegionallyAllCustomerAnalysis'
                title: Response Customer Sentiment Comments Region Api V1 Analysis
                  Sentiments Comments Region Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Commentators sentiments by region
      tags:
      - analysis_sentiments
  /api/v1/analysis_sentiments/reviews/category:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0441\u0435\u043D\
        \u0442\u0438\u043C\u0435\u043D\u0442 \u0430\u043D\u0430\u043B\u0438\u0437\
        \ \u0440\u0435\u0432\u044C\u044E\u0435\u0440\u043E\u0432 \u043F\u0440\u043E\
        \u0434\u0443\u043A\u0442\u0430 \u0441\u0433\u0440\u0443\u043F\u043F\u0438\u0440\
        \u043E\u0432\u0430\u043D\u043D\u044B\u0439 \u043F\u043E \u043A\u0430\u0442\
        \u0435\u0433\u043E\u0440\u0438\u044F\u043C"
      operationId: customer_sentiment_reviews_category_api_v1_analysis_sentiments_reviews_category_get
      parameters:
      - in: query
        name: product_name_id
        required: true
        schema:
          title: Product Name Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CustomersForAllCategoriesAnalysis'
                title: Response Customer Sentiment Reviews Category Api V1 Analysis
                  Sentiments Reviews Category Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Reviewers sentiments by category
      tags:
      - analysis_sentiments
  /api/v1/analysis_sentiments/reviews/region:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0441\u0435\u043D\
        \u0442\u0438\u043C\u0435\u043D\u0442 \u0430\u043D\u0430\u043B\u0438\u0437\
        \ \u0440\u0435\u0432\u044C\u044E\u0435\u0440\u043E\u0432 \u043F\u0440\u043E\
        \u0434\u0443\u043A\u0442\u0430 \u0441\u0433\u0440\u0443\u043F\u043F\u0438\u0440\
        \u043E\u0432\u0430\u043D\u043D\u044B\u0439 \u043F\u043E \u0440\u0435\u0433\
        \u0438\u043E\u043D\u0430\u043C"
      operationId: customer_sentiment_reviews_region_api_v1_analysis_sentiments_reviews_region_get
      parameters:
      - in: query
        name: product_name_id
        required: true
        schema:
          title: Product Name Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GroupRegionallyAllCustomerAnalysis'
                title: Response Customer Sentiment Reviews Region Api V1 Analysis
                  Sentiments Reviews Region Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Reviewers sentiments by region
      tags:
      - analysis_sentiments
  /api/v1/analysis_similarity/comments/reputation:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0430\u043D\u0430\
        \u043B\u0438\u0437 \u0441\u0445\u043E\u0436\u0435\u0441\u0442\u0438 \u043E\
        \u0442\u0437\u044B\u0432\u043E\u0432 \u043A\u0430\u0436\u0434\u043E\u0433\u043E\
        \ \u043A\u043B\u0438\u0435\u043D\u0442\u0430 \u0441\u043E \u0437\u043D\u0430\
        \u0447\u0435\u043D\u0438\u0435\u043C \u0440\u0435\u043F\u0443\u0442\u0430\u0446\
        \u0438\u0438."
      operationId: get_customer_similarity_analysis_product_by_comments_api_v1_analysis_similarity_comments_reputation_get
      parameters:
      - in: query
        name: product_name_id
        required: true
        schema:
          title: Product Name Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CustomerReputationAnalysisValue'
                title: Response Get Customer Similarity Analysis Product By Comments
                  Api V1 Analysis Similarity Comments Reputation Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Similarity comments customer analysis by product
      tags:
      - analysis_similarity
  /api/v1/analysis_similarity/reviews/reputation:
    get:
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0430\u043D\u0430\
        \u043B\u0438\u0437 \u0441\u0445\u043E\u0436\u0435\u0441\u0442\u0438 \u043E\
        \u0442\u0437\u044B\u0432\u043E\u0432 \u043A\u0430\u0436\u0434\u043E\u0433\u043E\
        \ \u043A\u043B\u0438\u0435\u043D\u0442\u0430 \u0441\u043E \u0437\u043D\u0430\
        \u0447\u0435\u043D\u0438\u0435\u043C \u0440\u0435\u043F\u0443\u0442\u0430\u0446\
        \u0438\u0438."
      operationId: get_customer_similarity_analysis_product_by_reviews_api_v1_analysis_similarity_reviews_reputation_get
      parameters:
      - in: query
        name: product_name_id
        required: true
        schema:
          title: Product Name Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CustomerReputationAnalysisValue'
                title: Response Get Customer Similarity Analysis Product By Reviews
                  Api V1 Analysis Similarity Reviews Reputation Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Similarity reviews customer analysis by product
      tags:
      - analysis_similarity
